### ISSUE TITLE
Double exception with Libraw 0.18.1

### ISSUE THREAD

**Issue by damonlynch** [photoshell/rawkit#121] opened 2017-03-09 00:16 UTC
I'm unsure if this is related to bug #93 or not, but I'm seeing this exception when using rawkit on a system with Libraw 0.18.1 (Ubuntu 17.04 devel in this instance):

Traceback (most recent call last):
  File "/home/damon/.local/lib/python3.5/site-packages/libraw/bindings.py", line 44, in __init__
    }[self.version_number[1]]
KeyError: 18

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/damon/zeromq_pyqt/zeromq_pyqt/raphodo/thumbnailextractor.py", line 276, in get_disk_photo_thumb
    with Raw(filename=full_file_name) as raw:
  File "/home/damon/.local/lib/python3.5/site-packages/rawkit/raw.py", line 70, in __init__
    self.libraw = LibRaw()
  File "/home/damon/.local/lib/python3.5/site-packages/libraw/bindings.py", line 47, in __init__
    'Unsupported Libraw version: %s.%s.%s.' % self.version_number
ImportError: Unsupported Libraw version: 0.18.1.

The line with zeromq in it refers to my code, Rapid Photo Downloader.

**Comment by campaul** [comment] 2017-03-13 00:48
#93 is the problem. Right now we only support versions 16 and 17. If you want you can try creating a `structs_18.py`, but that will require reading the LibRaw source code to figure out what the C structs look like for version 18. https://github.com/LibRaw/LibRaw/blob/0.18-stable/libraw/libraw_types.h is where the structs are defined if you want to take a stab at it.

**Comment by guillaume65** [comment] 2017-04-06 12:54
I do not consider myself a developer, but I am looking into creating a new structs file for the 0.18 version.
The LibRaw 0.18 versions contains some new structs which have to be defined in the new structs file, that should not be a problem.
I am uncertain about some of the datatypes, I would need some help in selecting the correct c_types.

Wim

**Comment by SamWhited** [comment] 2017-04-06 14:02
@guillaume65 great, thanks! Feel free to ask any specific questions you have here, or on #photoshell on Freenode ([webchat](https://webchat.freenode.net/?channels=photoshell)) if IRC is your thing.

**Comment by SamWhited** [comment] 2017-04-06 14:03
For now, let's close this as a duplicate of #93, we can continue discussion there if you want to update the structs. Thanks again!

**Closed by SamWhited** 2017-04-06 14:03 UTC

**Comment by guillaume65** [comment] 2017-04-07 17:48
Sam,

A few questions:

The C-struct libraw_output_params_t contains the following line:
`char **custom_camera_strings;`
I converted that to:
`('custom_camera_strings', POINTER(c_char_p)),`
Can you confirm this is correct?

I also modified the bindings.py file, to contain the version 18 of LibRaw.

I will now look into testing the new version and contact you later on committing the changes.

Wim
